; vim:et
expression = if-expression / term
term       = factor *(("+" / "-") factor)
factor     = unary *(("/" / "*") unary)
unary      = ("!" / "-") primary
primary    = value

equality-expression = comparison [("!=" / "==") comparison]
comparison = term [(">" / ">=" / "<" / "<=") term]

expression-with-paren = *c-wsp expression-with-paren-no-wsp *c-wsp
expression-with-paren-no-wsp = "(" *c-wsp expression *c-wsp ")"
expression-with-wsp = 1*c-wsp expression 1*c-wsp

expression-stmt = identifier
                       ("=" / "+=" / "-=" / "/=" / "*=")
                       expression
                       statement-end
