; vim:et
function-declaration = ["pub"] identifier-signature
function-signature = "fn"
                     ( (*c-wsp function-signature-arguments *c-wsp type)
                     / (1*c-wsp type) )
function-signature-arguments = "("
                               *c-wsp
                               identifier-signature
                               *(*c-wsp "," identifier-signature)
                               *c-wsp
                               ")"

function-definition = function-declaration *c-wsp "=" *WSP function-body
function-body = c-nl 1*function-body-element
function-body-element = 1*HTAB *SP statement
                      ; numbers of HTAB must be same in a function,
                      ; like [python](https://python.org)
                      ; statement has rule to match "*WSP c-nl"
