; vim:et
c-wsp = WSP / (c-nl WSP)
c-nl  = comment / CRLF
      ; comment or newline

file = *(toplevel-statement)

comment = ";" *(WSP / VCHAR) CRLF

toplevel-statement = declaration / definition

declaration = function-declaration

definition  = function-definition
